/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Glossary
         * @description Plain-English names for the internal identifiers.
         *
         *     Served from the backend so the labels sit beside the detectors they
         *     describe and cannot drift from them.
         */
        get: operations["read_glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Baseline Overview
         * @description What every merchant's baseline is currently built from.
         *
         *     The lag means a specific past day rolls into the window on the next
         *     run; `next_inclusion_date` names it, so the team can see which day is
         *     still open for review before it becomes part of normal.
         */
        get: operations["baseline_overview_api_baselines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: number;
            /** Merchant Id */
            merchant_id: string;
            /** Lane */
            lane: string;
            /** Blended Score */
            blended_score: number;
            /** Rank */
            rank: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Triggering Detectors */
            triggering_detectors: components["schemas"]["DetectorHit"][];
            /** Feature Snapshot */
            feature_snapshot: components["schemas"]["FeatureDivergence"][];
        };
        /**
         * BaselineOverview
         * @description What the baselines are built from, and what changes next run.
         */
        BaselineOverview: {
            /** Window Start */
            window_start: string | null;
            /** Window End */
            window_end: string | null;
            /** Window Days */
            window_days: number;
            /** Lag Days */
            lag_days: number;
            /** Next Inclusion Date */
            next_inclusion_date: string | null;
            /** Total Count */
            total_count: number;
            /** Usable Count */
            usable_count: number;
            /** Quarantined Total */
            quarantined_total: number;
            /** Merchants */
            merchants: components["schemas"]["BaselineRow"][];
        };
        /**
         * BaselineRow
         * @description One merchant's baseline provenance.
         */
        BaselineRow: {
            /** Merchant Id */
            merchant_id: string;
            /** Mcc */
            mcc: string | null;
            /** Lane */
            lane: string;
            /** Method */
            method: string;
            /** Usable */
            usable: boolean;
            /** Center */
            center: number | null;
            /** Observations */
            observations: number;
            /** Quarantined Days */
            quarantined_days: number;
            /** Peer Merchants */
            peer_merchants: number;
            /** Peer Usable */
            peer_usable: boolean;
            /** Volume Usable */
            volume_usable: boolean;
            /** Velocity Usable */
            velocity_usable: boolean;
            /** Is Ramp */
            is_ramp: boolean;
        };
        /** DetectorHit */
        DetectorHit: {
            /** Detector */
            detector: string;
            /** Sub Score */
            sub_score: number;
        };
        /** FeatureDivergence */
        FeatureDivergence: {
            /** Feature Name */
            feature_name: string;
            /** Merchant Value */
            merchant_value: number;
            /** Baseline Value */
            baseline_value: number;
            /** Deviation */
            deviation: number;
        };
        /**
         * Glossary
         * @description Every identifier that can reach a person, translated.
         */
        Glossary: {
            /** Detectors */
            detectors: components["schemas"]["GlossaryTerm"][];
            /** Features */
            features: components["schemas"]["GlossaryTerm"][];
            /** Lanes */
            lanes: components["schemas"]["GlossaryTerm"][];
            /** Baseline Methods */
            baseline_methods: components["schemas"]["GlossaryTerm"][];
        };
        /**
         * GlossaryTerm
         * @description One internal identifier and its plain-English rendering.
         */
        GlossaryTerm: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Meaning */
            meaning: string;
            /** Compared Against */
            compared_against: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_glossary_api_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Glossary"];
                };
            };
        };
    };
    baseline_overview_api_baselines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineOverview"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
        };
    };
    get_alert_api_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
