/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/glossary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Glossary
         * @description Plain-English names for the internal identifiers.
         *
         *     Served from the backend so the labels sit beside the detectors they
         *     describe and cannot drift from them.
         */
        get: operations["read_glossary_api_glossary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Baseline Overview
         * @description What every merchant's baseline is currently built from.
         *
         *     The lag means a specific past day rolls into the window on the next
         *     run; `next_inclusion_date` names it, so the team can see which day is
         *     still open for review before it becomes part of normal.
         */
        get: operations["baseline_overview_api_baselines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diagnostics
         * @description Why this alert fired: every detector's verdict, the statistics
         *     behind them, and the curves needed to plot the distributions.
         */
        get: operations["get_diagnostics_api_alerts__alert_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants/{merchant_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ledger
         * @description Every transaction a merchant processed on one local day.
         */
        get: operations["get_ledger_api_merchants__merchant_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertOut
         * @description An alert with enough merchant context to build the review header.
         *
         *     The metadata is joined at read time rather than copied into the alert row:
         *     a merchant's MCC description or district can be corrected later, and the
         *     header should show what is true now. The `feature_snapshot` stays frozen,
         *     because that is what the detector actually judged.
         */
        AlertOut: {
            /** Id */
            id: number;
            /** Merchant Id */
            merchant_id: string;
            /** Lane */
            lane: string;
            /** Blended Score */
            blended_score: number;
            /** Rank */
            rank: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Triggering Detectors */
            triggering_detectors: components["schemas"]["DetectorHit"][];
            /** Feature Snapshot */
            feature_snapshot: components["schemas"]["FeatureDivergence"][];
            /** Mcc */
            mcc?: string | null;
            /** Mcc Description */
            mcc_description?: string | null;
            /** Merchant District */
            merchant_district?: string | null;
            /** Merchant Subdistrict */
            merchant_subdistrict?: string | null;
            /** Business Nature */
            business_nature?: string | null;
            /** Merchant Status */
            merchant_status?: string | null;
            /** Scored Date */
            scored_date?: string | null;
            /** Alert Type */
            alert_type?: string | null;
        };
        /**
         * BaselineOverview
         * @description What the baselines are built from, and what changes next run.
         */
        BaselineOverview: {
            /** Window Start */
            window_start: string | null;
            /** Window End */
            window_end: string | null;
            /** Window Days */
            window_days: number;
            /** Lag Days */
            lag_days: number;
            /** Next Inclusion Date */
            next_inclusion_date: string | null;
            /** Total Count */
            total_count: number;
            /** Usable Count */
            usable_count: number;
            /** Quarantined Total */
            quarantined_total: number;
            /** Merchants */
            merchants: components["schemas"]["BaselineRow"][];
        };
        /**
         * BaselineRow
         * @description One merchant's baseline provenance.
         */
        BaselineRow: {
            /** Merchant Id */
            merchant_id: string;
            /** Mcc */
            mcc: string | null;
            /** Lane */
            lane: string;
            /** Method */
            method: string;
            /** Usable */
            usable: boolean;
            /** Center */
            center: number | null;
            /** Observations */
            observations: number;
            /** Quarantined Days */
            quarantined_days: number;
            /** Peer Merchants */
            peer_merchants: number;
            /** Peer Usable */
            peer_usable: boolean;
            /** Volume Usable */
            volume_usable: boolean;
            /** Velocity Usable */
            velocity_usable: boolean;
            /** Is Ramp */
            is_ramp: boolean;
        };
        /**
         * BaselineWindow
         * @description Which data formed the baseline this alert was judged against.
         */
        BaselineWindow: {
            /** Window Start */
            window_start: string | null;
            /** Window End */
            window_end: string | null;
            /** Window Days */
            window_days: number | null;
            /** Lag Days */
            lag_days: number | null;
            /** Quarantined Days */
            quarantined_days: number | null;
        };
        /** DetectorHit */
        DetectorHit: {
            /** Detector */
            detector: string;
            /** Sub Score */
            sub_score: number;
        };
        /**
         * DetectorVerdict
         * @description One detector's result, whether it fired or not. Showing the passes
         *     matters as much as the failures: it tells the analyst what was ruled out.
         */
        DetectorVerdict: {
            /** Rank */
            rank: number;
            /** Detector */
            detector: string;
            /** Label */
            label: string;
            /** Alert Type */
            alert_type: string;
            /** Compared Against */
            compared_against: string;
            /** Status */
            status: string;
            /** Merchant Value */
            merchant_value: number | string | null;
            /** Baseline Value */
            baseline_value: number | string | null;
            /** Deviation */
            deviation: number | null;
            /** Band */
            band: string | null;
            /** Message */
            message: string;
        };
        /** Diagnostics */
        Diagnostics: {
            /** Alert Id */
            alert_id: number;
            /** Merchant Id */
            merchant_id: string;
            /** Scored Date */
            scored_date: string;
            /** Root Cause */
            root_cause: string | null;
            /** Detectors */
            detectors: components["schemas"]["DetectorVerdict"][];
            statistics: components["schemas"]["Statistics"];
            hour_density: components["schemas"]["HourDensity"];
            peer_distribution: components["schemas"]["PeerDistribution"];
            window: components["schemas"]["BaselineWindow"];
        };
        /** FeatureDivergence */
        FeatureDivergence: {
            /** Feature Name */
            feature_name: string;
            /** Merchant Value */
            merchant_value: number;
            /** Baseline Value */
            baseline_value: number;
            /** Deviation */
            deviation: number;
        };
        /**
         * Glossary
         * @description Every identifier that can reach a person, translated.
         */
        Glossary: {
            /** Detectors */
            detectors: components["schemas"]["GlossaryTerm"][];
            /** Features */
            features: components["schemas"]["GlossaryTerm"][];
            /** Lanes */
            lanes: components["schemas"]["GlossaryTerm"][];
            /** Baseline Methods */
            baseline_methods: components["schemas"]["GlossaryTerm"][];
            /** Alert Types */
            alert_types: components["schemas"]["GlossaryTerm"][];
        };
        /**
         * GlossaryTerm
         * @description One internal identifier and its plain-English rendering.
         */
        GlossaryTerm: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Meaning */
            meaning: string;
            /** Compared Against */
            compared_against: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HourDensity
         * @description 96 bins of 15 minutes, for the KDE plot.
         */
        HourDensity: {
            /** Merchant */
            merchant: number[];
            /** Cohort */
            cohort: number[];
            /** Threshold */
            threshold: number;
            /** Cohort Threshold */
            cohort_threshold: number;
            /** Scored Day Hours */
            scored_day_hours: number[];
        };
        /** Ledger */
        Ledger: {
            /** Merchant Id */
            merchant_id: string;
            /** Date */
            date: string;
            /** Count */
            count: number;
            /** Total Amount */
            total_amount: number;
            /** Outlier Count */
            outlier_count: number;
            /** Transactions */
            transactions: components["schemas"]["LedgerRow"][];
        };
        /**
         * LedgerRow
         * @description One transaction on the scored day. No PAN hash — that is cardholder
         *     data and must not cross the API boundary.
         */
        LedgerRow: {
            /** Source Txn Id */
            source_txn_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Total Amount */
            total_amount: number;
            /** Net Amount */
            net_amount: number | null;
            /** Is Refund */
            is_refund: boolean;
            /** Card Type */
            card_type: string | null;
            /** Card Issuing Country */
            card_issuing_country: string | null;
            /** Card Issuing Bank */
            card_issuing_bank: string | null;
            /** Transaction Status */
            transaction_status: string | null;
            /** Currency */
            currency: string | null;
            /** Is Outlier */
            is_outlier: boolean;
        };
        /**
         * PeerDistribution
         * @description Where this merchant sits against its cohort, for the box plot.
         */
        PeerDistribution: {
            /** Merchant Value */
            merchant_value: number | null;
            /** Peer Median */
            peer_median: number | null;
            /** Peer Dispersion */
            peer_dispersion: number | null;
            /** Peer Q1 */
            peer_q1: number | null;
            /** Peer Q3 */
            peer_q3: number | null;
            /** Peer Upper Fence */
            peer_upper_fence: number | null;
            /** N Merchants */
            n_merchants: number;
            /** Peer Values */
            peer_values: number[];
        };
        /** StatBlock */
        StatBlock: {
            /** Mean */
            mean: number | null;
            /** Median */
            median: number | null;
            /** Mad */
            mad: number | null;
            /** N */
            n: number;
        };
        /** Statistics */
        Statistics: {
            merchant: components["schemas"]["StatBlock"];
            peer_mcc: components["schemas"]["StatBlock"];
            peer_subdistrict: components["schemas"]["StatBlock"];
            /** Modified Z */
            modified_z: number | null;
            /** Method */
            method: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_glossary_api_glossary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Glossary"];
                };
            };
        };
    };
    baseline_overview_api_baselines_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaselineOverview"];
                };
            };
        };
    };
    list_alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
        };
    };
    get_alert_api_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostics_api_alerts__alert_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ledger_api_merchants__merchant_id__transactions_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                merchant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ledger"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
