"""initial

Revision ID: 3cd2216f1a9f
Revises: 
Create Date: 2026-07-20 16:43:59.152971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd2216f1a9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('mcc', sa.String(), nullable=False),
    sa.Column('registered_address', sa.String(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lane', sa.String(), nullable=False),
    sa.Column('lane_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchants_mcc'), 'merchants', ['mcc'], unique=False)
    op.create_table('training_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('range_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('range_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lane', sa.String(), nullable=False),
    sa.Column('blended_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('triggering_detectors', sa.JSON(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_merchant_id'), 'alerts', ['merchant_id'], unique=False)
    op.create_table('merchant_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_profiles_as_of'), 'merchant_profiles', ['as_of'], unique=False)
    op.create_index(op.f('ix_merchant_profiles_merchant_id'), 'merchant_profiles', ['merchant_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_txn_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('terminal_id', sa.String(), nullable=True),
    sa.Column('card_bin', sa.String(), nullable=True),
    sa.Column('geo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_occurred_at'), 'transactions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_transactions_source_txn_id'), 'transactions', ['source_txn_id'], unique=True)
    op.create_table('dispositions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('risk_axis', sa.String(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=False),
    sa.Column('analyst_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositions_alert_id'), 'dispositions', ['alert_id'], unique=True)
    op.create_table('case_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disposition_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disposition_id'], ['dispositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_disposition_id'), 'case_events', ['disposition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_events_disposition_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_dispositions_alert_id'), table_name='dispositions')
    op.drop_table('dispositions')
    op.drop_index(op.f('ix_transactions_source_txn_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_occurred_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_merchant_profiles_merchant_id'), table_name='merchant_profiles')
    op.drop_index(op.f('ix_merchant_profiles_as_of'), table_name='merchant_profiles')
    op.drop_table('merchant_profiles')
    op.drop_index(op.f('ix_alerts_merchant_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('training_batches')
    op.drop_index(op.f('ix_merchants_mcc'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
