"""add alert as_of

Revision ID: 67c1c849ad0c
Revises: cf5321b31c4c
Create Date: 2026-07-30 14:26:09.998040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c1c849ad0c'
down_revision: Union[str, Sequence[str], None] = 'cf5321b31c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('as_of', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alerts_as_of'), 'alerts', ['as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_as_of'), table_name='alerts')
    op.drop_column('alerts', 'as_of')
    # ### end Alembic commands ###
