"""widen to real source schema

Revision ID: cf5321b31c4c
Revises: dd01c0a9b07a
Create Date: 2026-07-23 12:32:37.119997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5321b31c4c'
down_revision: Union[str, Sequence[str], None] = 'dd01c0a9b07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('mcc_description', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('agent_id', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('hashed_merchant_name', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('hashed_br_number', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('hashed_merchant_address', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('city', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('merchant_area', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('merchant_district', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('merchant_subdistrict', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('business_plan', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('business_nature', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('ownership_or_business_type', sa.String(), nullable=True))
    op.add_column('merchants', sa.Column('merchant_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_merchants_agent_id'), 'merchants', ['agent_id'], unique=False)
    op.create_index(op.f('ix_merchants_hashed_br_number'), 'merchants', ['hashed_br_number'], unique=False)
    op.create_index(op.f('ix_merchants_hashed_merchant_address'), 'merchants', ['hashed_merchant_address'], unique=False)
    op.create_index(op.f('ix_merchants_hashed_merchant_name'), 'merchants', ['hashed_merchant_name'], unique=False)
    op.create_index(op.f('ix_merchants_merchant_subdistrict'), 'merchants', ['merchant_subdistrict'], unique=False)
    op.add_column('transactions', sa.Column('card_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('card_origin', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('card_issuing_country', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('card_issuing_bank', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_gateway', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_status', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('hashed_pan', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_card_issuing_country'), 'transactions', ['card_issuing_country'], unique=False)
    op.create_index(op.f('ix_transactions_hashed_pan'), 'transactions', ['hashed_pan'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_status'), 'transactions', ['transaction_status'], unique=False)
    op.drop_column('transactions', 'terminal_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('terminal_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transactions_transaction_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_hashed_pan'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_card_issuing_country'), table_name='transactions')
    op.drop_column('transactions', 'hashed_pan')
    op.drop_column('transactions', 'transaction_status')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'payment_gateway')
    op.drop_column('transactions', 'card_issuing_bank')
    op.drop_column('transactions', 'card_issuing_country')
    op.drop_column('transactions', 'card_origin')
    op.drop_column('transactions', 'card_type')
    op.drop_index(op.f('ix_merchants_merchant_subdistrict'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_hashed_merchant_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_hashed_merchant_address'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_hashed_br_number'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_agent_id'), table_name='merchants')
    op.drop_column('merchants', 'merchant_status')
    op.drop_column('merchants', 'ownership_or_business_type')
    op.drop_column('merchants', 'business_nature')
    op.drop_column('merchants', 'business_plan')
    op.drop_column('merchants', 'merchant_subdistrict')
    op.drop_column('merchants', 'merchant_district')
    op.drop_column('merchants', 'merchant_area')
    op.drop_column('merchants', 'city')
    op.drop_column('merchants', 'hashed_merchant_address')
    op.drop_column('merchants', 'hashed_br_number')
    op.drop_column('merchants', 'hashed_merchant_name')
    op.drop_column('merchants', 'agent_id')
    op.drop_column('merchants', 'mcc_description')
    # ### end Alembic commands ###
